"""TP4 v29 release-functionality layer v2.

Parent: runtime_patch_dflash_tp4_v29_rc2.

This layer addresses the 2026-08-31 real-client runaway/stall incident without
changing allocator, DFlash math, request-wise q8, native assignment, or abort
cleanup semantics.

Two independent guards are added:

1. qwen3_coder streaming string-argument fix (upstream SGLang PR #25246).
   Large string tool parameters are emitted incrementally instead of being
   buffered until </parameter>.  This prevents a long write_file/content-style
   tool call from producing no SSE chunks while the model is still decoding.

2. OpenAI chat default completion cap.  Current SourceFind SGLang maps omitted
   max_tokens/max_completion_tokens to max_new_tokens=None, and the scheduler
   later treats None as 1<<30 capped only by context/pool limits.  On a 262144
   context server this can permit >100K completion tokens.  When BOTH OpenAI
   fields are omitted and to_sampling_params still returns None, set a bounded
   default (8192 by default). Explicit client limits are never changed.

Environment controls:
- SGLANG_Q38_QWEN3_CODER_STREAM_STRING_FIX=1|0 (default 1)
- SGLANG_Q38_OPENAI_DEFAULT_MAX_TOKENS=<int> (default 8192; 0 disables)

The vendored detector is generated by applying upstream PR #25246 commit
`eb25d35145e0a017e64c802e0ab9ed8c95a6bfa1` to the exact v29 production
runtime detector snapshot.  See upstream/patches and runtime_snapshots.
"""

from __future__ import annotations

import importlib.util
import os
import runpy
from pathlib import Path


_ROOT = "/data/qwen38-dflash2-k100ai"
if os.getenv("SGLANG_Q38_TP124_V30_SKIP_TP4_PARENT", "0") != "1":
    runpy.run_path(
        f"{_ROOT}/runtime_patch_dflash_tp4_v29_rc2_sitecustomize.py",
        run_name="__tp4_v29_rc3_parent__",
    )


def _env_bool(name: str, default: bool = True) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return str(raw).strip().lower() not in {"0", "false", "no", "off", ""}


def _env_nonnegative_int(name: str, default: int) -> int:
    raw = os.getenv(name)
    if raw is None or not str(raw).strip():
        return default
    try:
        value = int(raw)
    except (TypeError, ValueError) as exc:
        raise RuntimeError(f"{name} must be a non-negative integer, got {raw!r}") from exc
    if value < 0:
        raise RuntimeError(f"{name} must be >= 0, got {value}")
    return value


# ---------------------------------------------------------------------------
# 1) qwen3_coder: stream string-like tool parameters incrementally.
# ---------------------------------------------------------------------------
_STREAM_FIX_ENABLED = _env_bool("SGLANG_Q38_QWEN3_CODER_STREAM_STRING_FIX", True)
_STREAM_FIX_SOURCE = Path(__file__).with_name("qwen3_coder_detector_pr25246.py")

if _STREAM_FIX_ENABLED:
    if not _STREAM_FIX_SOURCE.is_file():
        raise RuntimeError(
            "v29-rc3 requires qwen3_coder_detector_pr25246.py beside sitecustomize.py"
        )

    _spec = importlib.util.spec_from_file_location(
        "q38_v29_qwen3_coder_detector_pr25246",
        str(_STREAM_FIX_SOURCE),
    )
    if _spec is None or _spec.loader is None:
        raise RuntimeError(f"cannot load {_STREAM_FIX_SOURCE}")
    _patched_qwen3 = importlib.util.module_from_spec(_spec)
    _spec.loader.exec_module(_patched_qwen3)

    from sglang.srt.function_call.function_call_parser import FunctionCallParser

    FunctionCallParser.ToolCallParserEnum["qwen3_coder"] = (
        _patched_qwen3.Qwen3CoderDetector
    )


# ---------------------------------------------------------------------------
# 2) Bound omitted OpenAI chat max_tokens/max_completion_tokens.
# ---------------------------------------------------------------------------
_DEFAULT_MAX_TOKENS = _env_nonnegative_int(
    "SGLANG_Q38_OPENAI_DEFAULT_MAX_TOKENS", 8192
)

from sglang.srt.entrypoints.openai.protocol import ChatCompletionRequest

_parent_chat_to_sampling_params = ChatCompletionRequest.to_sampling_params
_cap_hits = 0


def _chat_to_sampling_params_v2(
    self,
    stop,
    model_generation_config,
    tool_call_constraint=None,
):
    global _cap_hits
    out = _parent_chat_to_sampling_params(
        self,
        stop,
        model_generation_config,
        tool_call_constraint,
    )
    if (
        _DEFAULT_MAX_TOKENS > 0
        and self.max_completion_tokens is None
        and self.max_tokens is None
        and out.get("max_new_tokens") is None
    ):
        out["max_new_tokens"] = _DEFAULT_MAX_TOKENS
        _cap_hits += 1
        if _cap_hits <= 8 or _cap_hits % 128 == 0:
            print(
                "[K100 TP4 v29-rc3] ACTIVE default completion cap "
                f"hit={_cap_hits} max_new_tokens={_DEFAULT_MAX_TOKENS}",
                flush=True,
            )
    return out


if _DEFAULT_MAX_TOKENS > 0:
    ChatCompletionRequest.to_sampling_params = _chat_to_sampling_params_v2

print(
    "[K100 TP4 v29-rc3] installed: "
    f"qwen3_coder_stream_string_fix={int(_STREAM_FIX_ENABLED)} "
    f"openai_default_max_tokens={_DEFAULT_MAX_TOKENS}; "
    "parent v29-RC2 fast path + v29 allocator/DFlash path preserved",
    flush=True,
)
